kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: app-01-ingress

spec:
  rules:
    - host: 
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name:  app-01-svc-cl
                port:
                  number: 2345
